services:
  gateway:
    container_name: gateway-purch
    build:
      context: .
      dockerfile: dockerfile
    command: /app/gateway-purch
    ports:
      - "8080:8080"
    networks:
      - purch

networks:
  purch: