# https://taskfile.dev

version: '3'


tasks:
  build:
    cmds:
      - go build ./...

  lint:
    cmds:
      - golangci-lint run .

  run:
    cmds:
      - go run ./...

  vet:
    cmds:
      - go vet ./...

  test:
    cmds:
      - go test ./...
