# https://taskfile.dev

version: '3'


tasks:
  #################
  # docker cmds
  #################
  down:
    cmds:
      - docker compose --file=docker-compose.yml down

  up:
    cmds:
      - docker compose --file=docker-compose.yml up -d --build

  #############
  # go cmds
  #############
  build-go:
    cmds:
      - go build ./...

  lint:
    cmds:
      - golangci-lint run .

  run:
    cmds:
      - go run ./...

  vet:
    cmds:
      - go vet ./...

  test:
    cmds:
      - go test ./...
